apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-sdk-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator-sdk-practice
  template:
    metadata:
      labels:
        name: operator-sdk-practice
    spec:
      serviceAccountName: operator-sdk-practice
      containers:
        - name: operator-sdk-practice
          # Replace this with the built image name
          image: govargo/app-operator
          command:
          - operator-sdk-practice
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator-sdk-practice"
